routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

//Site\IndexController Routes
Route::get('/', 'Site\IndexController@index')->name('index')->middleware('language');
Route::post('/', 'Site\IndexController@login')->name('index')->middleware('language');

Route::any('/prevent', 'Site\IndexController@prevent');

Route::get('/firstlogin/{inviteToken}', 'Site\AccountController@createAccount')->name('create-account')->middleware('language');
Route::post('/firstlogin', 'Site\AccountController@SaveCreateAccount')->name('save-create-account')->middleware('language');

Route::get('/lang/{name}', 'Site\IndexController@setLang')->middleware('language');

Route::group(['middleware' => ['auth:web', 'permission', 'language']], function () {
    //Site\IndexController Routes
    Route::get('/profile', 'Site\ProfileController@profile')->name('profile');
    Route::post('/profile', 'Site\ProfileController@profileSave')->name('profile-save');

    Route::get('/language', 'Site\IndexController@languageManager')->name('manage-language-form');
    Route::post('/language', 'Site\IndexController@languageManager')->name('manage-language-save');
    Route::post('/language/restore', 'Site\IndexController@languageRestore')->name('manage-language-restore');

    Route::get('/vat-settings', 'SettingsController@vatSettings')->name('vat-settings-form');
    Route::get('/vat-settings/edit/{id}', 'SettingsController@editVatSettings')->name('edit-vat-settings');
    Route::post('/vat-settings', 'SettingsController@saveVatSettings')->name('save-vat-settings');

    Route::get('/out', 'Site\IndexController@logout')->middleware('language');

    //Company\HomeController Routes
    Route::get('/home', 'Company\HomeController@home')->name('dashboard');
    Route::get('/home/show-companies/{type}', 'Company\HomeController@showCompanies')->name('dashboard');
    Route::get('/home/show-invoice/{id?}', 'Company\HomeController@showInvoice')->name('dashboard');
    Route::get('/home/download-invoice-list/{id?}', 'Company\HomeController@downloadInvoiceList')->name('dashboard');
    
    Route::get('/list', 'Company\AdminController@listing')->name('customeradmin-list');
    Route::get('/subscription-list', 'Company\AdminController@subscriptionListing')->name('subscription-list');
    Route::post('/send-price-increase-request', 'Company\AdminController@sendPriceIncreaseRequest')->name('send-price-increase-request');
    Route::get('/view-detail/{id}', 'Company\AdminController@viewDetail')->name('view-detail');
    Route::get('/form', 'Company\AdminController@form')->name('customeradmin-form');
    Route::post('/form', 'Company\AdminController@formSave')->name('customeradmin-save');
    Route::get('/edit/{id}', 'Company\AdminController@edit')->name('customeradmin-edit');
    Route::get('/account-info/{id}', 'Company\AdminController@accountInfo')->name('customeradmin-edit');
    Route::get('/remove/{id}', 'Company\AdminController@remove')->name('customeradmin-remove');

    Route::get('/password', 'Company\AdminController@changePassword')->name('change-password-form');
    Route::post('/password', 'Company\AdminController@changePasswordSave')->name('change-password-save');

    Route::get('/permission/{id}', 'Company\HomeController@accessPermission')->name('access-permission-form');
    Route::post('/permission/{id}', 'Company\HomeController@accessPermissionSave')->name('access-permission-save');

    Route::group(['prefix' => 'audit'], function () {
        Route::get('/get-audit-type/{ref_id}/{type}', 'Audit\TypeController@getAuditType')->name('get-audit-type');
        Route::get('/exec-audit-type/{ref_id}', 'Audit\PlanningController@execAuditType')->name('exec-audit-type');

        //ISO clause
        Route::group(['prefix' => 'iso'], function () {
            Route::get('/list', 'Audit\IsoController@auditIsoList')->name('iso-list');
            Route::get('/form', 'Audit\IsoController@auditIsoForm')->name('iso-form');
            Route::post('/form', 'Audit\IsoController@auditIsoFormSave')->name('iso-save');
            Route::get('/edit/{id}', 'Audit\IsoController@auditIsoFormEdit')->name('iso-edit');
            Route::get('/delete/{id}', 'Audit\IsoController@auditIsoDelete')->name('iso-remove');
        });

        //Audit type
        Route::group(['prefix' => 'type'], function () {
            Route::get('/{id}', 'Audit\TypeController@auditTypeList')->name('audit-type-list');
            Route::get('/form/{id}', 'Audit\TypeController@auditTypeForm')->name('audit-type-form');
            Route::post('/save', 'Audit\TypeController@auditTypeSave')->name('audit-type-save');
            Route::get('/edit/{id}', 'Audit\TypeController@auditTypeEdit')->name('audit-type-edit');
            Route::get('/delete/{id}', 'Audit\TypeController@auditTypeDelete')->name('audit-type-delete');
        });
    });

    Route::group(['prefix' => 'package'], function () {
        Route::get('/list', 'Membership\PackageController@list')->name('package-list');
        Route::get('/form', 'Membership\PackageController@form')->name('package-form');
        Route::post('/form', 'Membership\PackageController@save')->name('package-save');
        Route::get('/edit/{id}', 'Membership\PackageController@edit')->name('package-edit');
        Route::get('/remove/{id}', 'Membership\PackageController@remove')->name('package-remove');
        Route::get('/user-plan', 'Membership\PackageController@userPlanlist')->name('user-plan-list');
        Route::get('/user-plan/edit/{id}', 'Membership\PackageController@edituserPlan')->name('user_plan-edit');
        Route::post('/user-plan', 'Membership\PackageController@userPlanSave')->name('user_plan-save');
    });

    Route::group(['prefix' => 'video'], function () {
        Route::get('/list', 'VideoController@list')->name('video-list');
        Route::get('/form', 'VideoController@form')->name('video-form');
        Route::post('/form', 'VideoController@save')->name('video-save');
        Route::get('/edit/{id}', 'VideoController@edit')->name('video-edit');
        Route::get('/delete/{id}', 'VideoController@delete')->name('video-delete');

        Route::get('/category/list', 'VideoController@catList')->name('video-cat-list');
        Route::get('/category/form', 'VideoController@catForm')->name('video-cat-form');
        Route::post('/category/form', 'VideoController@catFormSave')->name('video-cat-save');
        Route::get('/category/edit/{id}', 'VideoController@catFormEdit')->name('video-cat-edit');
        Route::get('/category/delete/{id}', 'VideoController@catDelete')->name('video-cat-remove');

        Route::get('/get-video-sub-category/{pid}','VideoController@getSubCategory')->name('video-sub-category');
        Route::get('/get-video-sub-category/{pid}/{selectedid}','VideoController@getSubCategory')->name('video-sub-category');
    });

    Route::get('/trial-period', 'SettingsController@generalSettings')->name('general-settings');
    Route::post('/trial-period', 'SettingsController@generalSettings')->name('general-settings');

    Route::get('/kpi-unit', 'SettingsController@kpiUnit')->name('kpi-unit');
    Route::post('/kpi-unit', 'SettingsController@kpiUnitSave')->name('kpi-unit');
    Route::get('/kpi-unit/data', 'SettingsController@kpiUnitData')->name('kpi-unit');

    Route::get('/getExport/{type}', 'Company\HomeController@getExport')->name('getExport');
});

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request')->middleware('language');;
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset')->middleware('language');;
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

app/Models/Kpi.php
<?php 

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Kpi extends Model
{
    use \App\Traits\CompanyCheckTraits;
    protected $table = "kpi";

    public function process()
    {
        return $this->belongsTo('App\Models\Process');
    }

    public function masterkpi()
    {
        return $this->hasMany('App\Models\KpiToMasterKpi', 'kpi_id', 'id');
    }

    public function kpiunit()
    {
        return $this->belongsTo('App\Models\KpiUnit', 'kpi_unit_id', 'id');
    }

    public function processkpi()
    {
        return $this->hasMany('App\Models\ProcessKpiData', 'kpi_id', 'id');
    }

    public function getValidFromAttribute($value)
    {
        return \Carbon\Carbon::parse($value)->format(\Config::get('settings.dashed_date'));
    }

    public function getValidToAttribute($value)
    {
        return \Carbon\Carbon::parse($value)->format(\Config::get('settings.dashed_date'));
    }
}

resources/views/includes/scripts/company_detail_script.blade.php
<script type="text/javascript">
	$(document).ready(function() {
		if($('#is_apply_vat').is(':checked')){
			$('#tva').prop('readonly',true);
			$('#tva').prop('required',false);
			$('#tva_label').removeClass('required');
			$('#tva').val('');
		}
		$(document).on('click', '#is_apply_vat', function() {
			if($(this).is(':checked') == true){
				$('#tva').prop('readonly',true);
				$('#tva').prop('required',false);
				$('#tva_label').removeClass('required');
				$('#tva').val('');
			}
			else{
				$('#tva').prop('readonly',false);
				$('#tva').prop('required',true);
				$('#tva_label').addClass('required');
			}
		})
		$('#cmpDetailFrm').on("submit", function()
		{ 
			var tva_no = $('#tva').val();
			var country = $('#country').val();
			var zip_code = $('#zip_code').val();
			var zip_validate = Validate_Zipcode(country,zip_code);
			var tva_validate = Validate_VATNumber(country,tva_no);
			if($('#is_apply_vat').is(':checked') == true){
				tva_validate = true;
			}
			if ((zip_validate == true && tva_validate == true) || (country != 1 && country != 2)) {
				$('#zip-error').html('');
				$('#tva-error').html('');
			} else {
				if (zip_validate == false) {
					if(country == 1){
						$('#zip-error').html("{{translate('words.zip_code_not_valid_for_belgium')}}");
					} else if(country == 2) {
						$('#zip-error').html("{{translate('words.zip_code_not_valid_for_netherland')}}");
					}
				} else {
					$('#zip-error').html('');
				}
				if (tva_validate == false) {
					if(country == 1){
						$('#tva-error').html("{{translate('words.tva_not_valid_for_belgium')}}");
					} else if(country == 2) {
						$('#tva-error').html("{{translate('words.tva_not_valid_for_netherland')}}");
					}
				} else {
					$('#tva-error').html('');
				}
				return false;
			}	
		})
	});

	function Validate_VATNumber(CountryCode, UsersVAT) {
		var VATreg = '';

		var validator = {
			'1' : function(){
				var reg = new RegExp(/^(BE)?\s?(\d\.?\-?\s?){1,}\d+$/ig);
				return reg.test(UsersVAT) && (!!UsersVAT.match(/\d/g) && UsersVAT.match(/\d/g).length == 10);
			},
			'2' : function(){
				var reg = new RegExp(/^(NL)?\s?(\d\.?\-?\s?){1,}(B\d{2})$/ig);
				return reg.test(UsersVAT) && (!!UsersVAT.match(/\d/g) && UsersVAT.match(/\d/g).length == 11);
			}
		};

		if (validator[CountryCode] && validator[CountryCode]()) {
			return true;
		} else {
			return false;
		}
	}

	function Validate_Zipcode(CountryCode, UsersVAT) {
		var VATreg = '';

		var validator = {
			'1' : function(){
				var reg = new RegExp(/^\d{4}$/ig);
				return reg.test(UsersVAT);
			},
			'2' : function(){
				var reg = new RegExp(/^\d{4}?\s?[a-z]{2}$/ig);
				return reg.test(UsersVAT);
			}
		};

		if(validator[CountryCode] && validator[CountryCode]()) {
			return true;
		}else {
			return false;
		}
	}
</script>

resources/views/includes/scripts/dashboard_issues_script.blade.php
@include('includes.chart_assets')
@stack('scripts')
<script type="text/javascript">
    $(document).ready(function() {
        $('.riskOpportunityCls').click(function () {
            sessionStorage.setItem("riskOrOpporId", $(this).data('riskoptid'));
            sessionStorage.setItem("riskOrOptType", $(this).data('type'));
            var processId = $(this).data("processid");
            $(location).attr('href', '{{url("/process/turtle")}}/' + processId);
        });
        $(document).on('click', '#planningTab', function () {
            $(location).attr('href', '{{url("/home/planning")}}');
        });
        $(document).on('click', '#cockpitTab', function () {
            $(location).attr('href', '{{url("/home")}}');
        });
        $(document).on('click', '#auditIssues', function () {
            $(location).attr('href', '{{url("/home/issues")}}');
        });
        $(document).on('click', '#auditMeeting', function () {
            $(location).attr('href', '{{url("/home/meeting")}}');
        });
        $(document).on('click', '#procesIssues', function () {
            $(location).attr('href', '{{url("/home/process_improvement")}}');
        });
        $(document).on('click', '#auditResult', function () {
            $(location).attr('href', '{{url("/home/audit_results")}}');
        });
        $(document).on('click', '#companyView', function () {
            $(location).attr('href', '{{url("/home/company-view")}}');
        });

        $('#not_started').click(function() {
            $('#closed').prop('checked', false);
            $('#ongoing').prop('checked', false);
            $('.not_started').show();
            if ($(this).is(':checked') == true) {
                $('.closed').hide();
                $('.ongoing').hide();
            }
            if ($(this).is(':checked') == false) {
                $('.closed').show();
                $('.ongoing').show();
            }
        });

        $('#ongoing').click(function() {
            $('#closed').prop('checked', false);
            $('#not_started').prop('checked', false);
            $('.ongoing').show();
            if ($(this).is(':checked') == true) {
                $('.closed').hide();
                $('.not_started').hide();
            }
            if ($(this).is(':checked') == false) {
                $('.closed').show();
                $('.not_started').show();
            }
        });

        $('#closed').click(function() {
            $('#not_started').prop('checked', false);
            $('#ongoing').prop('checked', false);
            $('.closed').show();
            if ($(this).is(':checked') == true) {
                $('.not_started').hide();
                $('.ongoing').hide();
            }
            if ($(this).is(':checked') == false) {
                $('.not_started').show();
                $('.ongoing').show();
            }
        });

        var dtsearchOption = $.extend({},
        $.datepicker.regional["{{session('lang')}}"], {
            dateFormat: "dd-mm-yy",
        });
        $(function() {
            $("#minDate").datepicker(dtsearchOption);
            $("#maxDate").datepicker(dtsearchOption);
        });
    });
</script>

resources/views/includes/scripts/kpi_relation_graph_script.blade.php
@include('includes.chart_assets')
@stack('scripts')
<script type="text/javascript">
$(document).ready(function() {
	    $.fn.extend({
	  	treeview: function() {
	    return this.each(function() {
	      // Initialize the top levels;
	      var tree = $(this);
	      
	      tree.addClass('treeview-tree');
	      tree.find('li').each(function() {
	        var stick = $(this);
	      });
	      tree.find('li').has("ul").each(function () {
	        var branch = $(this); //li with children ul
	        
	        branch.prepend("<i class='tree-indicator glyphicon glyphicon-chevron-right'></i>");
	        branch.addClass('tree-branch');
	        branch.on('click', function (e) {
	          if (this == e.target) {
	            var icon = $(this).children('i:first');
	            
	            icon.toggleClass("glyphicon-chevron-down glyphicon-chevron-right");
	            $(this).children().children().toggle();
	          }
	        })
	        branch.children().children().toggle();
	        branch.click();
	        branch.children('.tree-indicator, button, a').click(function(e) {
	          branch.click();
	          
	          e.preventDefault();
	        });
	      });
	    });
	  }
	});

	$(document).on("click", ".line-cls", function () {
	    $(".turtle-title").html("");
	    $(".turtle-body").html('<center><i class="fa fa-cog fa-spin fa-3x fa-fw text-system"></i></center>');
	    var id = $(this).data("id");
	    var model = $(this).data("model");
	    $.ajax({
	        url: "{{url('/process/turtle/graph')}}/" + id ,
	        type: "GET",
	        success: function (data) {
	        	$(".turtle-title").html(model);
	            $(".turtle-body").html(data);
	        }
	    });
	});
});

$(window).on('load', function () {
  $('.treeview').each(function () {
    var tree = $(this);
    tree.treeview();
  })
})
</script>

resources/views/includes/scripts/kpi_unit_script.blade.php
@include('includes.vue_assets')
@stack('scripts')
<script type="text/javascript">
	new Vue({
		el : '#kpi-unit',
		data : {
			units : {},
			edit : false,
			name_nl : '',
			name_en : '',
			name_fr : '',
			id : ''
		},
		created () {
			this.list();
		},
		filters : {
			format : function (val) {
				let lang = "{{session('lang')}}";
				switch(lang) {
					case "en": {
					  	return val.name_en;
					  	break;
					}
					case "fr": {
					  	return val.name_fr;
					  	break;
					}
					default: {
					  	return val.name_nl;
					  	break;
					}
				}
			}
		},
		methods : {
			list : function () {
				axios.get("{{url('/kpi-unit/data')}}")
				.then(response => {
					this.units = response.data;
				})
				.catch(console.log);
			},
			editData : function (each, i) {
				each.edit = true;
			},
			save : function (each, i) {
				each.edit = false;
				axios.post("{{url('/kpi-unit')}}", {
					'id' : each.id,
					'name_nl' : each.name_nl,
					'name_en' : each.name_en,
					'name_fr' : each.name_fr,
					'_token' : "{{csrf_token()}}"
				})
				.then(response => {
					let title = (response.data === false) ? "{{translate('words.faliure_message')}}" : "{{translate('words.success_message')}}";
                    let type = (response.data === false) ? "error" : "success";
                    new PNotify({
                        title: title,
                        text: "",
                        addclass: 'stack_top_right',
                        type: type,
                        width: '290px',
                        delay: 2000
                    });
				})
				.catch(console.log);
			}
		}
	});
</script>

resources/views/includes/scripts/master_kpi_data_script.blade.php
@include('includes.chart_assets')
@include('includes.vue_assets')
@stack('scripts')
<script type="text/javascript">
    Vue.component('period', {
        props: ['value'],
        template : `<input type="text" :value="value" />`,
        mounted : function () {
            var option = $.extend({},
            $.datepicker.regional["{{session('lang')}}"], {
                dateFormat: "dd-mm-yy",
                minDate: "{{date(Config::get('settings.dashed_date'), strtotime($details->valid_from))}}",
                maxDate: "{{date(Config::get('settings.dashed_date'), strtotime(date('Y-m-d')))}}", 
                onSelect: function () {
                    vm.period = this.value;
                }
            });
            $(this.$el).datepicker(option);
        }
    });

    Vue.component('kpi-list', {
        props : ['list', 'frequency'],
        data : function () {
            return {
                kpiUnit : "{{$details->kpi_unit_id}}",
                boolopt : {
                    '' : "{{translate('form.select')}}", 
                    '1' : "{{translate('words.true')}}", 
                    '0' : "{{translate('words.false')}}"
                },
                trendopt : {
                    '' : "{{translate('form.select')}}", 
                    '1' : "{{translate('words.up')}}", 
                    '0' : "{{translate('words.down')}}"
                }
            }
        },
        template : `
            <table class="table table-striped table-hover" id="datatable22" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th>{{translate('words.kpi_value')}}</th>
                        <th v-if="frequency == 'daily'">{{translate('form.day')}}</th> 
                        <th v-if="frequency=='weekly'">{{translate('form.weeknumber')}}</th> 
                        <th v-if="frequency=='monthly'">{{translate('form.monthnumber')}}</th> 
                        <th v-if="frequency=='quarterly'">{{translate('form.quarternumber')}}</th>
                        <th>{{translate('words.entry_date')}}</th>
                        <th>{{translate('table.operations')}}</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="each in list">
                        <td v-if="kpiUnit == 3">@{{boolopt[each.kpi_value]}}</td>
                        <td v-if="kpiUnit == 4">@{{trendopt[each.kpi_value]}}</td>
                        <td v-if="kpiUnit != 3 && kpiUnit != 4">@{{each.kpi_value}}</td>
                        <td>@{{each.period}}</td>
                        <td>@{{each.created_at}}</td>
                        <td>
                            <a href="javascript:void(0)" class="btn btn-default btn-sm" @click="editData(each)">
                                <span class="text-success fa fa-pencil"></span>
                            </a>
                            <a href="javascript:void(0);" class="btn btn-default btn-sm" @click="removeData(each.id)">
                                <span class="text-danger fa fa-trash"></span>
                            </a>
                        </td>
                    </tr>
                </tbody>
            </table>
        `,
        methods : {
            editData : function (data) {
                vm.edited = true;
                vm.target = data.kpi_value;
                vm.period = data.period;
                vm.targetBool = data.kpi_value;
                vm.trend = data.kpi_value;
                vm.hid = data.id;
                this.$nextTick(function () {
                    $('html, body').animate({
                        scrollTop: $("#kpidata").offset().top
                    }, 1000);
                    setTimeout(() => {
                        vm.targetClass = vm.targetBoolClass = vm.trendClass = 'form-control border-system';
                    }, 1000);
                });
            },
            removeData : function (id) {
                var confirmed = confirm("{{translate('alert.are_you_sure')}}");
                if (confirmed == true) {
                    axios.get("{{url('/master-kpi/dataremove')}}/" + id)
                    .then(response => {
                        new PNotify({
                            title : (response.data === false) ? "{{translate('words.you_dont_have_access')}}" : "{{translate('words.success_message')}}",
                            text : "",
                            addclass : 'stack_top_right',
                            type : (response.data === false) ? "error" : "success",
                            width : '290px',
                            delay : 2000
                        });
                    })
                    .then(() => {
                        vm.fetchData();
                        vm.fetchGraph();
                        vm.fetchRestricted();
                    });
                }
            }
        }
    });

    var vm = new Vue({
        el : '#kpidata',
        data : {
            list : [],
            frequency : "{{$details->frequency}}",
            weeks : {!! json_encode($weeks->weeks($details->valid_from, $details->valid_to)) !!},
            months : {!! json_encode($months->months($details->valid_from, $details->valid_to)) !!},
            quarters : {!! json_encode($quarters->quarters($details->valid_from, $details->valid_to)) !!},
            period : '{{($details->frequency == "daily" and strtotime($details->valid_from) < strtotime(date("d-m-Y")) and strtotime(date("d-m-Y")) < strtotime($details->valid_to)) ? date("d-m-Y") : ''}}',
            periodClass : 'form-control',
            restricted : [],
            masterId : "{{$details->id}}",
            kpiUnit : "{{$details->kpi_unit_id}}",
            boolOptions : {
                '' : "{{translate('form.select')}}", 
                '1' : "{{translate('words.true')}}", 
                '0' : "{{translate('words.false')}}"
            },
            trendOptions : {
                '' : "{{translate('form.select')}}", 
                '1' : "{{translate('words.up')}}", 
                '0' : "{{translate('words.down')}}"
            },
            target : '', targetClass : 'form-control', targetErr : '',
            targetBool : '', targetBoolClass : 'form-control',
            trend : '', trendClass : 'form-control',
            enabled : false,
            edited : false,
            hid : ''
        },
        created() {
            this.fetchData();
            this.fetchGraph();
            this.fetchRestricted();
        },
        watch : {
            list : function (val) {
                if ($.fn.dataTable.isDataTable('#datatable22')) {
                    $('#datatable22').DataTable().destroy();
                }
                setTimeout(() => {
                    $('#datatable22').DataTable(dtLangs);
                }, 100);
            },
            target : function (val) {
                if (val != '' && val.match(/^\d*\.?\d*$/) == null) {
                    this.targetClass = 'form-control error';
                    this.targetErr = "{{translate('alert.only_numeric_data_allowed')}}";
                } else {
                    this.targetClass = 'form-control';
                    this.targetErr = "";
                }
            },
            targetBool : function (val) {
                if (val != '') {
                    this.targetBoolClass = 'form-control';
                }
            },
            trend : function (val) {
                if (val != '') {
                    this.trendClass = 'form-control';
                }
            },
            period : function (val) {
                if (val != '') {
                    this.periodClass = 'form-control';
                }
            }
        },
        methods : {
            fetchRestricted : function () {
                axios.post("{{url('/master-kpi/datalist/restricted')}}", {
                    'segment' : 'master',
                    'id' : {{$details->id}},
                    'type' : "{{$details->frequency}}",
                    'from' : "{{$details->valid_from}}",
                    'to' : "{{$details->valid_to}}",
                    '_token' : "{{csrf_token()}}"
                })
                .then(response => {
                    this.restricted = response.data;
                })
                .catch(console.log);
            },
            fetchData: function () {
                axios.get("{{url('/master-kpi/datalist/'.$details->id.'/data')}}")
                .then(response => {
                    return new Promise((resolve, reject) => {
                        this.list = response.data;
                        resolve();
                    })
                })
                .catch(console.log);
            },
            fetchGraph : function () {
                axios.get("{{url('/master-kpi/datalist/'.$details->id.'/graph')}}")
                .then(response => {
                    this.label = response.data.label;
                    this.detail = response.data.detail;
                    var ctx = document.getElementById('master-kpi-graph').getContext('2d');
                    new Chart(ctx, {
                        type: 'line',
                        data: {
                            labels: response.data.label,
                            datasets: [{
                                label: "{{$details->name.' '.translate('words.graph')}}",
                                backgroundColor: 'rgb(255, 99, 132)',
                                borderColor: 'rgb(255, 99, 132)',
                                data: response.data.detail,
                            }]
                        },
                        options: {}
                    });
                });
            },
            saveData : function () {
                if (this.kpiUnit == 3 || this.kpiUnit == 4) {
                    this.target = '';
                }
                if (this.kpiUnit == 1 || this.kpiUnit == 2 || this.kpiUnit == 4) {
                    this.targetBool = '';
                }
                if (this.kpiUnit == 1 || this.kpiUnit == 2 || this.kpiUnit == 3) {
                    this.trend = '';
                }
                var errors = 0;
                if (this.period == "") {
                    this.periodClass = 'form-control error';
                    errors = 1;
                }
                if (this.kpiUnit == 1 || this.kpiUnit == 2) {
                    if (this.target == "" || this.target.match(/^\d*\.?\d*$/) == null) {
                        this.targetClass = 'form-control error';
                        errors = 1;
                    }
                }
                if (this.kpiUnit == 3) {
                    if (this.targetBool == '') {
                        this.targetBoolClass = 'form-control error';
                        errors = 1;
                    }
                }
                if (this.kpiUnit == 4) {
                    if (this.trend == '') {
                        this.trendClass = 'form-control error';
                        errors = 1;
                    }
                }
                if (errors == 0) {
                    this.enabled = true;
                    this.edited = false;
                    axios.post("{{url('/master-kpi/dataform')}}", {
                        'target' : this.target,
                        'targetBool' : this.targetBool,
                        'targetTrend' : this.trend,
                        'period' : this.period,
                        'hid' : this.hid,
                        'masterKpiId' : this.masterId,
                        '_token' : "{{csrf_token()}}"
                    })
                    .then(response => {
                        this.enabled = false;
                        new PNotify({
                            title : (response.data === false) ? "{{translate('words.faliure_message')}}" : "{{translate('words.success_message')}}",
                            text : "",
                            addclass : 'stack_top_right',
                            type : (response.data === false) ? "error" : "success",
                            width : '290px',
                            delay : 2000
                        });
                        this.fetchData();
                        this.fetchGraph();
                        this.fetchRestricted();
                        this.target = this.targetBool = this.trend = this.hid = this.period = '';
                    });
                }    
            }
        }
    });
</script>